export interface CityDistrictDatum {
  name: string
  value: number
}

export interface CityBoardDatum {
  id: string
  name: string
  enName: string
  center?: [number, number]
  value: number
  average: number
  districts?: CityDistrictDatum[]
}

export const zhejiangCityBoards: CityBoardDatum[] = [
  {
    id: 'shaoxingshi',
    name: '绍兴市',
    enName: 'SHAOXING',
    center: [120.636873, 29.734409],
    value: 0,
    average: 0,
    districts: [
      { name: '越城区', value: 0 },
      { name: '柯桥区', value: 0 },
      { name: '上虞区', value: 0 },
      { name: '嵊州市', value: 0 },
      { name: '诸暨市', value: 0 },
      { name: '新昌县', value: 0 },
    ],
  },
  {
    id: 'lishuishi',
    name: '丽水市',
    enName: 'LISHUI',
    center: [119.511104, 28.198908],
    value: 0,
    average: 0,
    districts: [
      { name: '莲都区', value: 0 },
      { name: '龙泉市', value: 0 },
      { name: '青田县', value: 0 },
      { name: '缙云县', value: 0 },
      { name: '景宁畲族自治县', value: 0 },
      { name: '遂昌县', value: 0 },
      { name: '松阳县', value: 0 },
      { name: '庆元县', value: 0 },
      { name: '云和县', value: 0 },
    ],
  },
  {
    id: 'quzhoushi',
    name: '衢州市',
    enName: 'QUZHOU',
    center: [118.674731, 28.93408],
    value: 0,
    average: 0,
    districts: [
      { name: '柯城区', value: 0 },
      { name: '衢江区', value: 0 },
      { name: '龙游县', value: 0 },
      { name: '常山县', value: 0 },
      { name: '开化县', value: 0 },
      { name: '江山市', value: 0 },
    ],
  },
  {
    id: 'wenzhoushi',
    name: '温州市',
    enName: 'WENZHOU',
    center: [120.462892, 27.895071],
    value: 0,
    average: 0,
    districts: [
      { name: '鹿城区', value: 0 },
      { name: '瓯海区', value: 0 },
      { name: '龙湾区', value: 0 },
      { name: '乐清市', value: 0 },
      { name: '瑞安市', value: 0 },
      { name: '永嘉县', value: 0 },
      { name: '平阳县', value: 0 },
      { name: '苍南县', value: 0 },
      { name: '文成县', value: 0 },
      { name: '泰顺县', value: 0 },
      { name: '洞头区', value: 0 },
      { name: '龙港市', value: 0 },
    ],
  },
  {
    id: 'taizhoushi',
    name: '台州市',
    enName: 'TAIZHOU',
    center: [121.137519, 28.756951],
    value: 0,
    average: 0,
    districts: [
      { name: '椒江区', value: 0 },
      { name: '黄岩区', value: 0 },
      { name: '路桥区', value: 0 },
      { name: '温岭市', value: 0 },
      { name: '临海市', value: 0 },
      { name: '玉环市', value: 0 },
      { name: '仙居县', value: 0 },
      { name: '天台县', value: 0 },
      { name: '三门县', value: 0 },
    ],
  },
  {
    id: 'zhoushanshi',
    name: '舟山市',
    enName: 'ZHOUSHAN',
    center: [122.181856, 30.118787],
    value: 0,
    average: 0,
    districts: [
      { name: '定海区', value: 0 },
      { name: '普陀区', value: 0 },
      { name: '岱山县', value: 0 },
      { name: '嵊泗县', value: 0 },
    ],
  },
  {
    id: 'ningboshi',
    name: '宁波市',
    enName: 'NINGBO',
    center: [121.479983, 29.729434],
    value: 0,
    average: 0,
    districts: [
      { name: '海曙区', value: 0 },
      { name: '鄞州区', value: 0 },
      { name: '江北区', value: 0 },
      { name: '镇海区', value: 0 },
      { name: '北仑区', value: 0 },
      { name: '奉化区', value: 0 },
      { name: '余姚市', value: 0 },
      { name: '慈溪市', value: 0 },
      { name: '象山县', value: 0 },
      { name: '宁海县', value: 0 },
    ],
  },
  {
    id: 'jiaxingshi',
    name: '嘉兴市',
    enName: 'JIAXING',
    center: [120.778861, 30.621856],
    value: 0,
    average: 0,
    districts: [
      { name: '南湖区', value: 0 },
      { name: '秀洲区', value: 0 },
      { name: '嘉善县', value: 0 },
      { name: '海宁市', value: 0 },
      { name: '平湖市', value: 0 },
      { name: '桐乡市', value: 0 },
      { name: '海盐县', value: 0 },
    ],
  },
  {
    id: 'jinhuashi',
    name: '金华市',
    enName: 'JINHUA',
    center: [119.951787, 29.11748],
    value: 0,
    average: 0,
    districts: [
      { name: '婺城区', value: 0 },
      { name: '金东区', value: 0 },
      { name: '兰溪市', value: 0 },
      { name: '东阳市', value: 0 },
      { name: '义乌市', value: 0 },
      { name: '永康市', value: 0 },
      { name: '武义县', value: 0 },
      { name: '浦江县', value: 0 },
      { name: '磐安县', value: 0 },
    ],
  },
  {
    id: 'huzhoushi',
    name: '湖州市',
    enName: 'HUZHOU',
    center: [119.868486, 30.744735],
    value: 0,
    average: 0,
    districts: [
      { name: '吴兴区', value: 0 },
      { name: '南浔区', value: 0 },
      { name: '德清县', value: 0 },
      { name: '长兴县', value: 0 },
      { name: '安吉县', value: 0 },
    ],
  },
  {
    id: 'hangzhoushi',
    name: '杭州市',
    enName: 'HANGZHOU',
    center: [119.468311, 29.899932],
    value: 0,
    average: 0,
    districts: [
      { name: '上城区', value: 0 },
      { name: '拱墅区', value: 0 },
      { name: '西湖区', value: 0 },
      { name: '滨江区', value: 0 },
      { name: '钱塘区', value: 0 },
      { name: '萧山区', value: 0 },
      { name: '余杭区', value: 0 },
      { name: '临平区', value: 0 },
      { name: '富阳区', value: 0 },
      { name: '临安区', value: 0 },
      { name: '建德市', value: 0 },
      { name: '桐庐县', value: 0 },
      { name: '淳安县', value: 0 },
    ],
  },
]
